site_name: DevOpsovich

theme:
  features:
      - content.code.annotate
      - content.code.select
      - content.code.copy
      - navigation.expand
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-4 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7

# extra_css:
  # - css/extra.css

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

repo_url: https://github.com/squidfunk/mkdocs-material
repo_name: squidfunk/mkdocs-material

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cosckoya
    - icon: fontawesome/brands/dev
      link: https://dev.to/cosckoya

plugins:
    - with-pdf:
    - glightbox:
    - search:
    - i18n:
        docs_structure: suffix
        languages:
          - locale: en
            name: English
            build: true
          - locale: ru
            name: Russia
            default: true
            build: true
