site_name: DevOps notes
site_url: https://betflop.github.io/

theme:
  features:
      - content.code.annotate
      - content.code.select
      - content.code.copy
      - navigation.expand
  name: material
  custom_dir: overrides
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-4 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7

# extra_css:
  # - css/extra.css

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

repo_url: https://github.com/betflop/betflop.github.io
repo_name: betflop.github.io

extra:
  analytics:
    provider: custom
  # analytics:
    # provider: google
    # property: G-MKNTDY3EFM
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/betflop
    - icon: fontawesome/brands/youtube
      link: https://youtube.com

plugins:
    - with-pdf:
    # - glightbox:
    - search:
    - i18n:
        docs_structure: suffix
        languages:
          - locale: en
            name: English
            build: true
          - locale: ru
            name: Russia
            default: true
            build: true
